export type TranscriptFetch = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;

export interface ExtractTranscriptOptions {
  fetch?: TranscriptFetch;
  signal?: AbortSignal;
  timeoutMs?: number;
}

export interface TranscriptSegment {
  start: number;
  text: string;
  timestamp: string;
}

export interface TranscriptResult {
  autogenerated: boolean;
  durationSeconds: number;
  languageCode: string;
  segments: TranscriptSegment[];
  srt: string;
  title: string;
  trackName: string;
  videoId: string;
  watchUrl: string;
}
