import { describe, expect, test } from "bun:test";

import { extractTranscript, parseYouTubeVideoId, segmentsToSrt } from "../src/index.js";

describe("transcript scraper", () => {
  test("parses common YouTube URL formats", () => {
    const id = "AMeSZvb_4FA";

    expect(parseYouTubeVideoId(id)).toBe(id);
    expect(parseYouTubeVideoId(`https://youtu.be/${id}`)).toBe(id);
    expect(parseYouTubeVideoId(`https://www.youtube.com/watch?v=${id}&t=4s`)).toBe(id);
    expect(parseYouTubeVideoId(`https://youtube.com/shorts/${id}`)).toBe(id);
    expect(parseYouTubeVideoId(`https://youtube.com/embed/${id}`)).toBe(id);
  });

  test("rejects non-YouTube and malformed URLs", () => {
    expect(() => parseYouTubeVideoId("https://example.com/watch?v=AMeSZvb_4FA")).toThrow();
    expect(() => parseYouTubeVideoId("not a URL")).toThrow();
    expect(() => parseYouTubeVideoId("https://youtube.com/watch?v=short")).toThrow();
  });

  test("formats timestamped segments as SRT", () => {
    const srt = segmentsToSrt(
      [
        { start: 4, text: "Hello", timestamp: "0:04" },
        { start: 9.5, text: "World", timestamp: "0:09" },
      ],
      12,
    );

    expect(srt).toMatch(/00:00:04,000 --> 00:00:09,499/);
    expect(srt).toMatch(/00:00:09,500 --> 00:00:11,999/);
    expect(srt).toContain("Hello");
    expect(srt).toContain("World");
  });

  test("extracts a typed transcript from a URL", async () => {
    const videoId = "AMeSZvb_4FA";
    const initialData = {
      section: {
        videoDescriptionTranscriptSectionRenderer: {
          primaryButton: {
            buttonRenderer: {
              command: {
                commandExecutorCommand: {
                  commands: [
                    {
                      showEngagementPanelEndpoint: {
                        globalConfiguration: { params: "panel-params" },
                        identifier: { tag: "transcript-panel" },
                      },
                    },
                  ],
                },
              },
            },
          },
        },
      },
    };
    const playerResponse = {
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [
            { kind: "asr", languageCode: "en", name: { simpleText: "English (auto)" } },
          ],
        },
      },
      playabilityStatus: { status: "OK" },
      videoDetails: { lengthSeconds: "12", title: "Test video" },
    };
    const html = [
      `var ytInitialData = ${JSON.stringify(initialData)};`,
      `var ytInitialPlayerResponse = ${JSON.stringify(playerResponse)};`,
      '"INNERTUBE_API_KEY":"test-key"',
      '"INNERTUBE_CLIENT_VERSION":"1.2.3"',
    ].join("\n");
    const panelData = {
      content: {
        engagementPanelSectionListRenderer: {
          content: {
            sectionListRenderer: {
              contents: [
                {
                  itemSectionRenderer: {
                    contents: [
                      {
                        macroMarkersPanelItemViewModel: {
                          item: {
                            timelineItemViewModel: {
                              contentItems: [
                                {
                                  transcriptSegmentViewModel: {
                                    simpleText: "Hello world",
                                    timestamp: "0:04",
                                  },
                                },
                              ],
                            },
                          },
                        },
                      },
                    ],
                  },
                },
              ],
            },
          },
        },
      },
    };
    const requests: string[] = [];

    const result = await extractTranscript(`https://youtu.be/${videoId}`, {
      fetch: async (input) => {
        const url = String(input);
        requests.push(url);
        return url.includes("/watch?") ? new Response(html) : Response.json(panelData);
      },
    });

    expect(requests).toHaveLength(2);
    expect(result.videoId).toBe(videoId);
    expect(result.title).toBe("Test video");
    expect(result.autogenerated).toBe(true);
    expect(result.segments).toEqual([{ start: 4, text: "Hello world", timestamp: "0:04" }]);
    expect(result.srt).toContain("Hello world");
  });
});
