import type { UIMessage } from "ai";

export type HearingStatus = "ready" | "processing" | "failed";

export interface TranscriptSegment {
  id: string;
  hearingId: string;
  position: number;
  startSeconds: number;
  endSeconds: number;
  timestamp: string;
  text: string;
}

export interface Hearing {
  id: string;
  videoId: string;
  title: string;
  description: string;
  thumbnailUrl: string;
  watchUrl: string;
  publishedText: string;
  durationSeconds: number;
  languageCode: string;
  trackName: string;
  autogenerated: boolean;
  status: HearingStatus;
  segmentCount: number;
  chunkCount: number;
  ingestedAt: string;
}

export interface HearingDetail extends Hearing {
  segments: TranscriptSegment[];
}

export interface HearingChunk {
  id: string;
  hearingId: string;
  videoId: string;
  title: string;
  text: string;
  startSeconds: number;
  endSeconds: number;
  startSegment: number;
  endSegment: number;
  segmentIds: string[];
}

export interface HearingCitation extends HearingChunk {
  score: number;
  timestamp: string;
  watchUrl: string;
}

export interface ConversationSummary {
  id: string;
  hearingId: string;
  title: string;
  activeStreamId: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Conversation extends ConversationSummary {
  messages: UIMessage[];
}

export interface IngestVideoCandidate {
  videoId: string;
  title: string;
  watchUrl: string;
  thumbnailUrl: string;
  publishedText: string;
  durationText: string;
  description: string;
}
