import fs from "node:fs";
import path from "node:path";
import Database from "better-sqlite3";
import { env } from "@/lib/env";

declare global {
  var __ragHorDatabase: Database.Database | undefined;
}

function initialize(database: Database.Database) {
  database.pragma("journal_mode = WAL");
  database.pragma("foreign_keys = ON");
  database.exec(`
    CREATE TABLE IF NOT EXISTS hearings (
      id TEXT PRIMARY KEY,
      video_id TEXT NOT NULL UNIQUE,
      title TEXT NOT NULL,
      description TEXT NOT NULL DEFAULT '',
      thumbnail_url TEXT NOT NULL,
      watch_url TEXT NOT NULL,
      published_text TEXT NOT NULL DEFAULT '',
      duration_seconds REAL NOT NULL DEFAULT 0,
      language_code TEXT NOT NULL DEFAULT 'en',
      track_name TEXT NOT NULL DEFAULT '',
      autogenerated INTEGER NOT NULL DEFAULT 0,
      status TEXT NOT NULL DEFAULT 'processing',
      segment_count INTEGER NOT NULL DEFAULT 0,
      chunk_count INTEGER NOT NULL DEFAULT 0,
      ingested_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS transcript_segments (
      id TEXT PRIMARY KEY,
      hearing_id TEXT NOT NULL REFERENCES hearings(id) ON DELETE CASCADE,
      position INTEGER NOT NULL,
      start_seconds REAL NOT NULL,
      end_seconds REAL NOT NULL,
      timestamp TEXT NOT NULL,
      text TEXT NOT NULL,
      UNIQUE(hearing_id, position)
    );
    CREATE INDEX IF NOT EXISTS idx_segments_hearing_time
      ON transcript_segments(hearing_id, start_seconds);

    CREATE TABLE IF NOT EXISTS conversations (
      id TEXT PRIMARY KEY,
      hearing_id TEXT NOT NULL REFERENCES hearings(id) ON DELETE CASCADE,
      title TEXT NOT NULL DEFAULT 'New inquiry',
      active_stream_id TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_conversations_hearing_updated
      ON conversations(hearing_id, updated_at DESC);

    CREATE TABLE IF NOT EXISTS messages (
      id TEXT PRIMARY KEY,
      conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
      role TEXT NOT NULL,
      parts_json TEXT NOT NULL,
      created_at TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_messages_conversation_created
      ON messages(conversation_id, created_at ASC);
  `);
}

export function getDatabase() {
  if (globalThis.__ragHorDatabase) return globalThis.__ragHorDatabase;
  fs.mkdirSync(path.dirname(env.databasePath), { recursive: true });
  const database = new Database(env.databasePath);
  initialize(database);
  globalThis.__ragHorDatabase = database;
  return database;
}
