import type { Hearing, HearingDetail, TranscriptSegment } from "@/lib/types";
import { getDatabase } from "@/server/db";

interface HearingRow {
  id: string;
  video_id: string;
  title: string;
  description: string;
  thumbnail_url: string;
  watch_url: string;
  published_text: string;
  duration_seconds: number;
  language_code: string;
  track_name: string;
  autogenerated: number;
  status: Hearing["status"];
  segment_count: number;
  chunk_count: number;
  ingested_at: string;
}

interface SegmentRow {
  id: string;
  hearing_id: string;
  position: number;
  start_seconds: number;
  end_seconds: number;
  timestamp: string;
  text: string;
}

function mapHearing(row: HearingRow): Hearing {
  return {
    id: row.id,
    videoId: row.video_id,
    title: row.title,
    description: row.description,
    thumbnailUrl: row.thumbnail_url,
    watchUrl: row.watch_url,
    publishedText: row.published_text,
    durationSeconds: row.duration_seconds,
    languageCode: row.language_code,
    trackName: row.track_name,
    autogenerated: Boolean(row.autogenerated),
    status: row.status,
    segmentCount: row.segment_count,
    chunkCount: row.chunk_count,
    ingestedAt: row.ingested_at,
  };
}

function mapSegment(row: SegmentRow): TranscriptSegment {
  return {
    id: row.id,
    hearingId: row.hearing_id,
    position: row.position,
    startSeconds: row.start_seconds,
    endSeconds: row.end_seconds,
    timestamp: row.timestamp,
    text: row.text,
  };
}

export function listHearings(): Hearing[] {
  const rows = getDatabase()
    .prepare("SELECT * FROM hearings WHERE status = 'ready' ORDER BY ingested_at DESC")
    .all() as HearingRow[];
  return rows.map(mapHearing);
}

export function getHearing(id: string): HearingDetail | null {
  const database = getDatabase();
  const row = database.prepare("SELECT * FROM hearings WHERE id = ?").get(id) as HearingRow | undefined;
  if (!row) return null;
  const segments = database
    .prepare("SELECT * FROM transcript_segments WHERE hearing_id = ? ORDER BY position ASC")
    .all(id) as SegmentRow[];
  return { ...mapHearing(row), segments: segments.map(mapSegment) };
}

export function getHearingByVideoId(videoId: string): Hearing | null {
  const row = getDatabase().prepare("SELECT * FROM hearings WHERE video_id = ?").get(videoId) as
    | HearingRow
    | undefined;
  return row ? mapHearing(row) : null;
}

export function upsertHearing(input: Hearing, segments: TranscriptSegment[]) {
  const database = getDatabase();
  const upsert = database.transaction(() => {
    database
      .prepare(`
        INSERT INTO hearings (
          id, video_id, title, description, thumbnail_url, watch_url, published_text,
          duration_seconds, language_code, track_name, autogenerated, status,
          segment_count, chunk_count, ingested_at
        ) VALUES (
          @id, @videoId, @title, @description, @thumbnailUrl, @watchUrl, @publishedText,
          @durationSeconds, @languageCode, @trackName, @autogenerated, @status,
          @segmentCount, @chunkCount, @ingestedAt
        )
        ON CONFLICT(video_id) DO UPDATE SET
          id = excluded.id,
          title = excluded.title,
          description = excluded.description,
          thumbnail_url = excluded.thumbnail_url,
          watch_url = excluded.watch_url,
          published_text = excluded.published_text,
          duration_seconds = excluded.duration_seconds,
          language_code = excluded.language_code,
          track_name = excluded.track_name,
          autogenerated = excluded.autogenerated,
          status = excluded.status,
          segment_count = excluded.segment_count,
          chunk_count = excluded.chunk_count,
          ingested_at = excluded.ingested_at
      `)
      .run({ ...input, autogenerated: input.autogenerated ? 1 : 0 });

    database.prepare("DELETE FROM transcript_segments WHERE hearing_id = ?").run(input.id);
    const insert = database.prepare(`
      INSERT INTO transcript_segments (
        id, hearing_id, position, start_seconds, end_seconds, timestamp, text
      ) VALUES (@id, @hearingId, @position, @startSeconds, @endSeconds, @timestamp, @text)
    `);
    for (const segment of segments) insert.run(segment);
  });
  upsert();
}
