import { createHash } from "node:crypto";
import { extractTranscript, parseYouTubeVideoId } from "@repo/transcript-scraper";
import { chunkTranscript } from "../src/lib/chunk-transcript";
import { env, requireModelConfiguration } from "../src/lib/env";
import { fetchChannelVideos, selectHearingCandidates } from "../src/lib/channel";
import { formatTimestamp, youtubeThumbnailUrl, youtubeWatchUrl } from "../src/lib/time";
import type { Hearing, IngestVideoCandidate, TranscriptSegment } from "../src/lib/types";
import { upsertHearing } from "../src/server/hearings";
import { replaceHearingChunks } from "../src/server/qdrant";

const VERIFIED_SAMPLE_IDS = ["h1PGUlEDJ78", "2Qak3EhQp_s", "eGnBueKsfRk", "jQwsQPh6m1g", "SuTZM0EP3D4"];

function argumentValue(name: string) {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

function hasArgument(name: string) {
  return process.argv.includes(name);
}

function log(stage: string, message: string) {
  console.log(`${new Date().toLocaleTimeString()}  ${stage.padEnd(11)} ${message}`);
}

function hearingId(videoId: string) {
  return `hor-${createHash("sha1").update(videoId).digest("hex").slice(0, 12)}`;
}

const sleep = (milliseconds: number) => new Promise((resolve) => setTimeout(resolve, milliseconds));

async function fetchTranscriptWithRetry(candidate: IngestVideoCandidate) {
  const attempts = 3;
  let lastError: unknown;

  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      return await extractTranscript(candidate.watchUrl);
    } catch (error) {
      lastError = error;
      const message = error instanceof Error ? error.message : String(error);
      const retryable = /empty transcript|returned 429|timed out|fetch failed/i.test(message);
      if (!retryable || attempt === attempts) throw error;
      const delay = attempt * 1_500;
      log("RETRY", `${candidate.videoId} · ${message}; retrying in ${delay / 1000}s (${attempt}/${attempts})`);
      await sleep(delay);
    }
  }

  throw lastError;
}

async function candidates(): Promise<IngestVideoCandidate[]> {
  const explicit = argumentValue("--video");
  if (explicit) {
    const videoId = parseYouTubeVideoId(explicit);
    return [
      {
        videoId,
        title: videoId,
        watchUrl: youtubeWatchUrl(videoId),
        thumbnailUrl: youtubeThumbnailUrl(videoId),
        publishedText: "",
        durationText: "",
        description: "",
      },
    ];
  }

  if (hasArgument("--channel")) {
    const limit = Number(argumentValue("--limit") ?? 5);
    log("FETCH", `Reading ${env.youtubeChannelUrl}`);
    return selectHearingCandidates(await fetchChannelVideos(env.youtubeChannelUrl), limit);
  }

  const sampleSize = Number(argumentValue("--sample") ?? 5);
  const catalog = await fetchChannelVideos(env.youtubeChannelUrl).catch(() => []);
  const metadata = new Map(catalog.map((candidate) => [candidate.videoId, candidate]));
  return VERIFIED_SAMPLE_IDS.slice(0, sampleSize).map(
    (videoId) =>
      metadata.get(videoId) ?? {
        videoId,
        title: videoId,
        watchUrl: youtubeWatchUrl(videoId),
        thumbnailUrl: youtubeThumbnailUrl(videoId),
        publishedText: "",
        durationText: "",
        description: "",
      },
  );
}

async function ingest(candidate: IngestVideoCandidate) {
  log("FETCH", `${candidate.videoId} · fetching YouTube transcript`);
  const transcript = await fetchTranscriptWithRetry(candidate);
  const id = hearingId(transcript.videoId);
  const segments: TranscriptSegment[] = transcript.segments.map((segment, position, all) => ({
    id: `${id}:segment:${position}`,
    hearingId: id,
    position,
    startSeconds: segment.start,
    endSeconds: all[position + 1]?.start ?? Math.min(transcript.durationSeconds, segment.start + 8),
    timestamp: segment.timestamp || formatTimestamp(segment.start),
    text: segment.text,
  }));

  log("CHUNK", `${transcript.videoId} · ${segments.length} timed segments`);
  const chunks = chunkTranscript({ id, videoId: transcript.videoId, title: transcript.title }, segments);
  log("EMBED", `${transcript.videoId} · ${chunks.length} citation-aware chunks`);
  await replaceHearingChunks(id, chunks);

  const hearing: Hearing = {
    id,
    videoId: transcript.videoId,
    title: transcript.title,
    description: candidate.description,
    thumbnailUrl: candidate.thumbnailUrl || youtubeThumbnailUrl(transcript.videoId),
    watchUrl: transcript.watchUrl,
    publishedText: candidate.publishedText,
    durationSeconds: transcript.durationSeconds,
    languageCode: transcript.languageCode,
    trackName: transcript.trackName,
    autogenerated: transcript.autogenerated,
    status: "ready",
    segmentCount: segments.length,
    chunkCount: chunks.length,
    ingestedAt: new Date().toISOString(),
  };
  upsertHearing(hearing, segments);
  log("STORE", `${transcript.videoId} · saved SQLite metadata + transcript`);
  return hearing;
}

async function main() {
  console.log("\nRAG-HOR ingestion\n────────────────────────────────────────────────────────");
  requireModelConfiguration();
  log("CONFIG", `Gateway ready · ${env.embeddingModel} · ${env.embeddingDimensions} dimensions`);
  const selected = await candidates();
  log("SELECT", `${selected.length} video(s) queued`);
  let succeeded = 0;
  for (const [index, candidate] of selected.entries()) {
    console.log(`\n[${index + 1}/${selected.length}] ${candidate.title}`);
    try {
      const hearing = await ingest(candidate);
      succeeded += 1;
      log("READY", `${hearing.title} (${formatTimestamp(hearing.durationSeconds)})`);
    } catch (error) {
      log("FAILED", `${candidate.videoId} · ${error instanceof Error ? error.message : String(error)}`);
    }
  }
  console.log(`\nDone: ${succeeded}/${selected.length} hearing(s) ready.\n`);
  if (selected.length > 0 && succeeded === 0) process.exitCode = 1;
}

main().catch((error) => {
  console.error("\nIngestion stopped:", error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
